version: "3"

services:
  postgres-keycloak:
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./:/app
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
