server:
  port: 8081

spring:
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        event.merge.entity_copy_observer: allow
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    locations: classpath:db/migration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/keycloak
    driver-class-name: org.postgresql.Driver
    username: keycloak
    password: keycloak
    hikari:
      minimum-idle: 10
      maximum-pool-size: 70
      idle-timeout: 600000
      connection-test-query: SELECT 1
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: login-app
#            authorization-grant-type: authorization_code
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: http://10.125.142.3:8089/auth/realms/My_realm
#            user-name-attribute: preferred_username
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8484/auth/realms/my_realm
#        registration:
#          keycloak:
#            client-id: my_client

#
keycloak:
  auth-server-url: http://10.125.142.3:8089
  realm: my_realm
  resource: my_client
#  public-client: true
#  ssl-required: external
#  credentials:
#    secret: FwbAFIQJU0BdKiVeqKrW5TzhtVt2QjI5
#  bearer-only: true
#  principal-attribute: preferred_username
#  use-resource-role-mappings: true