CREATE TABLE USERS
(
    ID                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME                    VARCHAR(255),
    SERVICE_RENDERED        VARCHAR(255),
    ADDRESS                 VARCHAR(255),
    CONSTRAINT pk_customer  PRIMARY KEY (id)
);